//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Auth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthInitParameters) DeepCopyInto(out *AuthInitParameters) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = new(string)
		**out = **in
	}
	if in.Fqdn != nil {
		in, out := &in.Fqdn, &out.Fqdn
		*out = new(string)
		**out = **in
	}
	if in.NsGroup != nil {
		in, out := &in.NsGroup, &out.NsGroup
		*out = new(string)
		**out = **in
	}
	if in.RestartIfNeeded != nil {
		in, out := &in.RestartIfNeeded, &out.RestartIfNeeded
		*out = new(bool)
		**out = **in
	}
	if in.SoaDefaultTTL != nil {
		in, out := &in.SoaDefaultTTL, &out.SoaDefaultTTL
		*out = new(float64)
		**out = **in
	}
	if in.SoaExpire != nil {
		in, out := &in.SoaExpire, &out.SoaExpire
		*out = new(float64)
		**out = **in
	}
	if in.SoaNegativeTTL != nil {
		in, out := &in.SoaNegativeTTL, &out.SoaNegativeTTL
		*out = new(float64)
		**out = **in
	}
	if in.SoaRefresh != nil {
		in, out := &in.SoaRefresh, &out.SoaRefresh
		*out = new(float64)
		**out = **in
	}
	if in.SoaRetry != nil {
		in, out := &in.SoaRetry, &out.SoaRetry
		*out = new(float64)
		**out = **in
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
	if in.ZoneFormat != nil {
		in, out := &in.ZoneFormat, &out.ZoneFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthInitParameters.
func (in *AuthInitParameters) DeepCopy() *AuthInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthList) DeepCopyInto(out *AuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Auth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthList.
func (in *AuthList) DeepCopy() *AuthList {
	if in == nil {
		return nil
	}
	out := new(AuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthObservation) DeepCopyInto(out *AuthObservation) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = new(string)
		**out = **in
	}
	if in.Fqdn != nil {
		in, out := &in.Fqdn, &out.Fqdn
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InternalID != nil {
		in, out := &in.InternalID, &out.InternalID
		*out = new(string)
		**out = **in
	}
	if in.NsGroup != nil {
		in, out := &in.NsGroup, &out.NsGroup
		*out = new(string)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.RestartIfNeeded != nil {
		in, out := &in.RestartIfNeeded, &out.RestartIfNeeded
		*out = new(bool)
		**out = **in
	}
	if in.SoaDefaultTTL != nil {
		in, out := &in.SoaDefaultTTL, &out.SoaDefaultTTL
		*out = new(float64)
		**out = **in
	}
	if in.SoaExpire != nil {
		in, out := &in.SoaExpire, &out.SoaExpire
		*out = new(float64)
		**out = **in
	}
	if in.SoaNegativeTTL != nil {
		in, out := &in.SoaNegativeTTL, &out.SoaNegativeTTL
		*out = new(float64)
		**out = **in
	}
	if in.SoaRefresh != nil {
		in, out := &in.SoaRefresh, &out.SoaRefresh
		*out = new(float64)
		**out = **in
	}
	if in.SoaRetry != nil {
		in, out := &in.SoaRetry, &out.SoaRetry
		*out = new(float64)
		**out = **in
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
	if in.ZoneFormat != nil {
		in, out := &in.ZoneFormat, &out.ZoneFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthObservation.
func (in *AuthObservation) DeepCopy() *AuthObservation {
	if in == nil {
		return nil
	}
	out := new(AuthObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthParameters) DeepCopyInto(out *AuthParameters) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExtAttrs != nil {
		in, out := &in.ExtAttrs, &out.ExtAttrs
		*out = new(string)
		**out = **in
	}
	if in.Fqdn != nil {
		in, out := &in.Fqdn, &out.Fqdn
		*out = new(string)
		**out = **in
	}
	if in.NsGroup != nil {
		in, out := &in.NsGroup, &out.NsGroup
		*out = new(string)
		**out = **in
	}
	if in.RestartIfNeeded != nil {
		in, out := &in.RestartIfNeeded, &out.RestartIfNeeded
		*out = new(bool)
		**out = **in
	}
	if in.SoaDefaultTTL != nil {
		in, out := &in.SoaDefaultTTL, &out.SoaDefaultTTL
		*out = new(float64)
		**out = **in
	}
	if in.SoaExpire != nil {
		in, out := &in.SoaExpire, &out.SoaExpire
		*out = new(float64)
		**out = **in
	}
	if in.SoaNegativeTTL != nil {
		in, out := &in.SoaNegativeTTL, &out.SoaNegativeTTL
		*out = new(float64)
		**out = **in
	}
	if in.SoaRefresh != nil {
		in, out := &in.SoaRefresh, &out.SoaRefresh
		*out = new(float64)
		**out = **in
	}
	if in.SoaRetry != nil {
		in, out := &in.SoaRetry, &out.SoaRetry
		*out = new(float64)
		**out = **in
	}
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(string)
		**out = **in
	}
	if in.ZoneFormat != nil {
		in, out := &in.ZoneFormat, &out.ZoneFormat
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthParameters.
func (in *AuthParameters) DeepCopy() *AuthParameters {
	if in == nil {
		return nil
	}
	out := new(AuthParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthStatus) DeepCopyInto(out *AuthStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthStatus.
func (in *AuthStatus) DeepCopy() *AuthStatus {
	if in == nil {
		return nil
	}
	out := new(AuthStatus)
	in.DeepCopyInto(out)
	return out
}
