// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ViewInitParameters struct {

	// Comment for the DNS View object; maximum 256 characters.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// The Extensible attributes of the DNS view to be added/updated, as a map in JSON format
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// The name of the DNS View to be specified
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the Network View in which DNS View exists.
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`
}

type ViewObservation struct {

	// Comment for the DNS View object; maximum 256 characters.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// The Extensible attributes of the DNS view to be added/updated, as a map in JSON format
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// The name of the DNS View to be specified
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the Network View in which DNS View exists.
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`

	// NIOS object's reference, not to be set by a user.
	Ref *string `json:"ref,omitempty" tf:"ref,omitempty"`
}

type ViewParameters struct {

	// Comment for the DNS View object; maximum 256 characters.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// The Extensible attributes of the DNS view to be added/updated, as a map in JSON format
	// +kubebuilder:validation:Optional
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// The name of the DNS View to be specified
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the Network View in which DNS View exists.
	// +kubebuilder:validation:Optional
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`
}

// ViewSpec defines the desired state of View
type ViewSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ViewParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ViewInitParameters `json:"initProvider,omitempty"`
}

// ViewStatus defines the observed state of View.
type ViewStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ViewObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// View is the Schema for the Views API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infoblox}
type View struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ViewSpec   `json:"spec"`
	Status ViewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ViewList contains a list of Views
type ViewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []View `json:"items"`
}

// Repository type metadata.
var (
	View_Kind             = "View"
	View_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: View_Kind}.String()
	View_KindAPIVersion   = View_Kind + "." + CRDGroupVersion.String()
	View_GroupVersionKind = CRDGroupVersion.WithKind(View_Kind)
)

func init() {
	SchemeBuilder.Register(&View{}, &ViewList{})
}
